copy /y Terminal.ico "%LOCALAPPDATA%\Microsoft\WindowsApps"
reg add "HKCU\Software\Classes\Directory\shell\Open Terminal here\command" /d "\"%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe\" -d \"%%V\"
reg add "HKCU\Software\Classes\Directory\shell\Open Terminal here" /v icon /t REG_SZ /d "%LOCALAPPDATA%\Microsoft\WindowsApps\Terminal.ico" 
reg add "HKCU\Software\Classes\Directory\Background\shell\Open Terminal here\command" /d "\"%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe\" -d \"%%V\"
reg add "HKCU\Software\Classes\Directory\Background\shell\Open Terminal here" /v icon /t REG_SZ /d "%LOCALAPPDATA%\Microsoft\WindowsApps\Terminal.ico" 
reg add "HKCU\Software\Classes\Drive\shell\Open Terminal here\command" /d "\"%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe\" -d \"%%V\"
reg add "HKCU\Software\Classes\Drive\shell\Open Terminal here" /v icon /t REG_SZ /d "%LOCALAPPDATA%\Microsoft\WindowsApps\Terminal.ico" 
reg add "HKCU\Software\Classes\LibraryFolder\Background\shell\Open Terminal here\command" /d "\"%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe\" -d \"%%V\"
reg add "HKCU\Software\Classes\LibraryFolder\Background\shell\Open Terminal here" /v icon /t REG_SZ /d "%LOCALAPPDATA%\Microsoft\WindowsApps\Terminal.ico" 